### ISSUE TITLE
bin/dev crashes on new app

### ISSUE THREAD

**Issue by diegomichel** [rails/jsbundling-rails#166] opened 2023-08-24 07:15 UTC
On Mac when using the bin/dev script the web server crashes, here are the logs. Please excuse me if this is not the correct gem to report this :).

```
~/github/pmt (4-testing-tools ✗) bin/dev
00:06:49 web.1  | started with pid 45581
00:06:49 js.1   | started with pid 45582
00:06:49 css.1  | started with pid 45583
00:06:49 js.1   | yarn run v1.22.15
00:06:49 css.1  | yarn run v1.22.15
00:06:49 js.1   | $ esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds --public-path=/assets --watch
00:06:49 css.1  | $ tailwindcss -i ./app/assets/stylesheets/application.tailwind.css -o ./app/assets/builds/application.css --minify --watch
00:06:50 js.1   | [watch] build finished, watching for changes...
00:06:50 web.1  | DEBUGGER: Debugger can attach via UNIX domain socket (/var/folders/kv/16w8qw0d0dxg1nnm0lc34glc0000gn/T/ruby-debug-sock-501/ruby-debug-diegomichelrubioramirez-45584)
00:06:50 web.1  | #<Thread:0x000000010d938240@DEBUGGER__::Server::reader /Users/diegomichelrubioramirez/.rvm/gems/ruby-3.1.2/gems/debug-1.8.0/lib/debug/server.rb:44 run> terminated with exception (report_on_exception is true):
00:06:50 web.1  | /Users/diegomichelrubioramirez/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:1116:in `unix': too long unix socket path (109 bytes given but 104 bytes max) (ArgumentError)
00:06:50 web.1  |       from /Users/diegomichelrubioramirez/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:1116:in `unix_server_socket'
00:06:50 web.1  |       from /Users/diegomichelrubioramirez/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:1164:in `unix_server_loop'
00:06:50 web.1  |       from /Users/diegomichelrubioramirez/.rvm/gems/ruby-3.1.2/gems/debug-1.8.0/lib/debug/server.rb:500:in `accept'
00:06:50 web.1  |       from /Users/diegomichelrubioramirez/.rvm/gems/ruby-3.1.2/gems/debug-1.8.0/lib/debug/server.rb:49:in `block in activate'
00:06:50 web.1  | #<Thread:0x000000010d938010@DEBUGGER__::SESSION@server /Users/diegomichelrubioramirez/.rvm/gems/ruby-3.1.2/gems/debug-1.8.0/lib/debug/session.rb:179 aborting> terminated with exception (report_on_exception is true):
00:06:50 web.1  | /Users/diegomichelrubioramirez/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:1116:in `unix': too long unix socket path (109 bytes given but 104 bytes max) (ArgumentError)
00:06:50 web.1  |       from /Users/diegomichelrubioramirez/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:1116:in `unix_server_socket'
00:06:50 web.1  |       from /Users/diegomichelrubioramirez/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:1164:in `unix_server_loop'
00:06:50 web.1  |       from /Users/diegomichelrubioramirez/.rvm/gems/ruby-3.1.2/gems/debug-1.8.0/lib/debug/server.rb:500:in `accept'
00:06:50 web.1  |       from /Users/diegomichelrubioramirez/.rvm/gems/ruby-3.1.2/gems/debug-1.8.0/lib/debug/server.rb:49:in `block in activate'
00:06:50 web.1  | /Users/diegomichelrubioramirez/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:1116:in `unix': too long unix socket path (109 bytes given but 104 bytes max) (ArgumentError)
00:06:50 web.1  |       from /Users/diegomichelrubioramirez/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:1116:in `unix_server_socket'
00:06:50 web.1  |       from /Users/diegomichelrubioramirez/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:1164:in `unix_server_loop'
00:06:50 web.1  |       from /Users/diegomichelrubioramirez/.rvm/gems/ruby-3.1.2/gems/debug-1.8.0/lib/debug/server.rb:500:in `accept'
00:06:50 web.1  |       from /Users/diegomichelrubioramirez/.rvm/gems/ruby-3.1.2/gems/debug-1.8.0/lib/debug/server.rb:49:in `block in activate'
00:06:50 web.1  | exited with code 1
00:06:50 system | sending SIGTERM to all processes
00:06:50 css.1  | exited with code 1
00:06:50 js.1   | exited with code 1
```

Looks like env command on `Procfile.dev` might be causing the issue, probably an env var?

changing `env RUBY_DEBUG_OPEN=true bin/rails server` to just `env bin/rails server` fixes the issue 🤔 .

**Comment by phantomwhale** [comment] 2023-08-28 06:08
I've been hitting a similar issue:

```
my-app-1 | 05:50:27 web.1  |   Rendered text template (Duration: 0.0ms | Allocations: 24)
my-app-1 | 05:50:27 web.1  | Completed 200 OK in 452ms (Views: 4.8ms | ActiveRecord: 2.8ms | Allocations: 28169)
my-app-1 | 05:50:27 web.1  |
my-app-1 | 05:50:27 web.1  |
my-app-1 | 05:50:27 web.1  | Started GET "/assets/fonts/Graphik-Medium-aeec9e6cbb82ed00c2bf827ef56ac0099bb39112.woff2" for 172.18.0.1 at 2023-08-28 05:50:27 +0000
my-app-1 | 05:50:27        | exited with code 0
my-app-1 | 05:50:27 system | sending SIGTERM to all processes
my-app-1 | 05:50:27 web.1  | [8] === puma shutdown: 2023-08-28 05:50:27 +0000 ===
my-app-1 | 05:50:27 web.1  | [8] - Goodbye!
my-app-1 | 05:50:27 web.1  | [8] - Gracefully shutting down workers...
my-app-1 | 05:50:27 js.1   | exited with code 1
my-app-1 | 05:50:27 web.1  | Not notifying due to an invalid api_key
my-app-1 | 05:50:27 css.1  | exited with code 1
my-app-1 | 05:50:27 web.1  | terminated by SIGTERM
my-app-1 exited with code 0
```

Was wondering if the ruby debugger was the culprit in my case - the `exited with code 0` doesn't appear to be any of the sub-processes (as it has no name?) - but it seems to send the SIGTERM killer to all the running processes.

**Comment by matt17r** [comment] 2023-11-01 06:25
This is happening to me too... Mac OS Sonoma 14.1, Ruby 3.2.2 and Rails 7.1.1. No docker.

Like the OP, it seems to be caused by `env RUBY_DEBUG_OPEN=true` in `Procfile.dev`. If I remove that environment variable it starts up fine.

**Comment by matt17r** [comment] 2023-11-01 11:04
Figured it out @diegomichel. It's because we have long computer usernames. Ruby debug [generates a socket name that is too long](https://github.com/ruby/debug/issues/982). Yours is 24 characters (diegomichelrubioramirez) and mine is 23 (matthewlindfieldseager). Suggest you close this issue and plus one the issue there. 

@phantomwhale, your issue looks different. Ours was crashing at Rails startup, yours is crashing during the app lifecycle.

**Closed** 2024-01-05 14:18 UTC
